### ISSUE TITLE
Error with joining and watching video, same client keeps joining over and over

### ISSUE THREAD

**Issue by Shroopy** [dyc3/opentogethertube#1565]
### Current Behavior

My friend is trying to join the room but the video isn't consistently playing or being watchable. While they try to watch, new clients keep being created with the same name. When they tried with a different browser, it created a new name for them but the same issue. This happened both on chrome and edge, both with no extensions.

### Expected Behavior

People should be able to join normally.

### Steps To Reproduce

1. Be my friend
2. Join the room

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

![image](https://github.com/dyc3/opentogethertube/assets/46693163/1a609c9f-db03-487e-8ae5-aa8e2e67927e)
I'm not sure what other information would be helpful to gather.

**Comment by dyc3** [comment]
I checked the logs and I'm pretty sure I know what the problem is. Room names are supposed to be case-insensitive, but for whatever reason trying to join the all lowercase version of the room was not putting you in the room if you had different casing.

I'll have a fix out soon, but if this happens again, make sure the letter casing in the link you share matches what appears in your browser after you've joined the room.
