### ISSUE TITLE
Client gets redirected to incorrect page

### ISSUE THREAD

**Issue by RedFish87** [dyc3/opentogethertube#1808]
### Current Behavior

Hi,

My permanent rooms just disappeared. Am I doing anything wrong? Please help

### Expected Behavior

Permanent rooms exist.

### Steps To Reproduce

1. Create a permanent room
2. Wait a day
3. Room gone ("Disconnected")

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Room name or URL

https://opentogethertube.com/rooms/English

**Comment by dyc3** [comment]
Good news is your room still exists on the backend, but I need to do some digging to see why it's throwing you out of the room.

**Comment by dyc3** [comment]
I've figured out what's happening. This is only a client side bug. 

Workaround: Directly navigate to the room instead of clicking a link.
- Copy the URL of the room
- Open a new tab
- Paste it in the address bar and press enter

Reproduction:
- Click a link to a room in a web page
- See that you get redirected to `/room/:roomId`
- See not found screen

**Comment by RedFish87** [comment]
Thanks a lot for such a quick response! You're kind to do this and what
more, on a Sunday. I've tried out the solution and it seems to be working 🙏

Dne ne 27. 10. 2024 12:32 uživatel Carson McManus ***@***.***>
napsal:
