### ISSUE TITLE
Split the room view into smaller components

### ISSUE THREAD

**Issue by Butt4cak3** [dyc3/opentogethertube#281]
The Room.vue file has become quite large and deals with a bunch of things that could be split up into several files. In fact, I already made a video player component that abstracts away the different video services.

This issue is supposed to act as a means of discussing and tracking the progress of changes I want to make to the room view. If you disagree with these decisions or want to add something to the list, let me know.

I was thinking about extracting the following components:

- [x] Video player (#282)
- [x] Chat (#283)
- [x] Video queue
- [x] Video search
- [x] User list (?)
- [x] Invite box (?)

**Comment by dyc3** [comment]
The video player and chat probably make the most sense to move to their own components. I don't think it would make a lot of sense to make the video queue and search parts into their own components, because most of their functionality is handled by `VideoQueueItem`. User list would probably be fine to seperate, but idk. I don't think the invite box will ever be used in another location, nor big enough to warrant being moved to a separate component.

**Comment by Butt4cak3** [comment]
> please keep PRs small

No worries. I plan to create separate PRs for every entry in the list.

I started with the video player in #282 because I already had it pretty much done yesterday.
