### ISSUE TITLE
Clicking on the video to pause/play is unresponsive

### ISSUE THREAD

**Issue by elenirotsides** [dyc3/opentogethertube#322]
## Current Behavior

When you try to click on the video to pause/play (like you would in a YouTube video), instead of pausing/playing, this functionality is unresponsive. 

### How To Reproduce

1. Navigate to a room in OTT
2. Add a video
3. Begin watching the video
4. Click anywhere on the video to try and pause/play
5. Notice that the video does not respond to this request

## Expected behavior
Similar to how YouTube does this, I should be able to click on the video and pause/play.

### Screenshots

I have a screen recording: 
https://gyazo.com/20dbc81b3b0bba4fbe229c521c1eb201

## Environment

- [x] This happens on the official site: opentogethertube.com
- [x] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

### Desktop (please complete the following information when applicable):
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 86.0.4240.183

**Comment by dyc3** [comment]
This is intentional. When you click the video, you're telling the youtube player _directly_ to toggle playback. We need to know if the user is trying to play/pause the video so we can keep all the clients in sync. When the playback state changes, the client immediately changes it back to match the room state.
