### ISSUE TITLE
Eslint rules are not being enforced correctly

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#323]
## Current Behavior

`vue-cli-service lint` doesn't like to enforce eslint rules outside of the `src` directory.

## Expected behavior

Eslint rules should be enforced all the time, for every file.

#### Additional context

I think this is a consequence of globbing the server and client together like we have it now.

**Comment by Butt4cak3** [comment]
I can't get the tests to show me linting errors *at all*. Am I doing something wrong? I'm running `npm run test` while having files with linting errors both inside and outside of `src` but I don't get any linting information at all.

**Comment by dyc3** [comment]
`npm run lint` runs the linter

**Comment by Butt4cak3** [comment]
I know. But we're talking about `vue-cli-service test:unit` here, aren't we?

**Comment by dyc3** [comment]
No. `npm run test` does not run the linter at all.

**Comment by Butt4cak3** [comment]
That's what I was saying. The test suite doesn't do linting. I thought that maybe you tried to set it up to do both because the issue description says
> `vue-cli-service test:unit` doesn't like to enforce eslint rules outside of the `src` directory.
but I guess you meant to write `vue-cli-service lint`.

Either way, I found the solution. The `vue-cli-service lint` command has an optional positional `files` argument.

```
$ npx vue-cli-service lint --help

  Usage: vue-cli-service lint [options] [...files]
...
```

The default value for this argument is `src`, `test` and root config files, [defined in @vue/cli-plugin-eslint](https://github.com/vuejs/vue-cli/blob/fe88b1c7c61e9fe9e5a3a9a1fe54ec4ab9a77845/packages/%40vue/cli-plugin-eslint/lint.js#L56-L62). To override this behaviour, you can change the `lint` script to run `vue-cli-service lint .` (note the dot).

**Comment by dyc3** [comment]
Oh wait I typoed, updating the original issue
