### ISSUE TITLE
Loop mode

### ISSUE THREAD

**Issue by Butt4cak3** [dyc3/opentogethertube#334]
**Is your feature request related to a problem? Please describe.**
A friend of mine asked if we could add a loop mode where the same video would play over and over again without any interaction.

**Describe the solution you'd like**
I was thinking that a somewhat easy way to implement this would be to re-queue the current video as soon as it starts playing. That way, the whole queue would run in a loop.

**Comment by firestar9114** [comment]
I would also really like this feature, but I don't know if adding more videos to the queue is really the right answer.  My use case is I've started prepping D&D sessions with watch2gether actually, but that can't loop videos either.  When I prep a session I want to be able to add all the music themes and character themes.  Because I don't know how long these scenes are going to last(how long my players are going to chat to a character or stay in an area) it would be really, really nice to be able to feed it a video and just have it always loop until I click on another entry in the queue.  I've started using voicemod for some Sfx and Music, but it is a real pain to download everything as most of my music I want to use is on youtube and I have bookmarks linking to like 200 songs all sorted in my browser already with group speed dial.  But to play them over discord in voice mod I need to run my downloader, strip the video, run it through my converter, and only then will voicemod play it.  This completely breaks the flow of a session obviously, and discord's sound quality is terrible.  Thus I was hoping for a solution like this so I can just have everyone open a tab, put it in the background and it can run natively in an embedded YT player in the background in their browser.

Sadly, while I'm familiar with Asm, C, C++, C#, and Java, I know practically nothing about web development, so I am humbly requesting here that you add this feature.

**Comment by dyc3** [comment]
That's a really interesting use case. It might warrant a new queue mode.
We could very easily have it loop the whole queue, or a single item.

Unfortunately, I'm super busy with finals coming up right now, and I won't be able to work on this until late May at minimum.
