### ISSUE TITLE
ENABLE_YOUTUBE_SEARCH is missing

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#339]
When we refactored the info extractor, we lost the ability to use the `ENABLE_YOUTUBE_SEARCH` config environment variable.

For reference:
- When `ENABLE_YOUTUBE_SEARCH` is omitted, default to `0`
- When `ENABLE_YOUTUBE_SEARCH == 0`, non-url add previews throw `FeatureDisabledException`
- When `ENABLE_YOUTUBE_SEARCH==1`, non-url add previews are allowed

**Comment by Butt4cak3** [comment]
Oh, right. I didn't use this because I made the info extractor so that you could theoretically use any adapter (or combination of adapters) for searches. I thought that maybe the best way would be to add a dropdown menu to the search bar. But there should still be a way to let hosters configure which adapters have searches enabled and which don't.
