### ISSUE TITLE
Add player layout mode that spans entire width of the screen

### ISSUE THREAD

**Issue by xRealNeon** [dyc3/opentogethertube#644]
### Is your feature request related to a problem? Please describe.

Yes, Please bring back the theater mode

### Describe the solution you'd like

Please bring back the theater mode

**Comment by dyc3** [comment]
It's a little unclear what you are looking for. Can you elaborate? The player's size was changed to resemble youtube's theater mode more closely. Do you want the player to be larger? I intentionally don't want the player size to be too big, because it's annoying to need to scroll down in order to see the video from top to bottom when the page is first loaded.

**Comment by xRealNeon** [comment]
Yeah, I liked the old size. Please add a switch or something to enable the old bigger one.

**Comment by dyc3** [comment]
I'm messing with the player size, and I'm having trouble getting it to be much larger without compromising UX. The size difference from doesn't really make a huge difference, imo. Is fullscreen mode not sufficient for you? You can still scroll down an access the queue while in fullscreen mode.

**Comment by xRealNeon** [comment]
Can't you just add a button to make it like it was before?
I updated my instance today and then had this new layout but found the old one much better.

**Comment by dyc3** [comment]
> Can't you just add a button to make it like it was before?

I don't want it the way it was before because the player with the chat closed was _too big_. It required users to scroll down in order to find the queue/add/settings tabs, which is pretty critical to communicating how to use the site without adding an explicit tutorial. Nobody likes tutorials, and if a tutorial is needed then the UI is too complicated.

In the old layout, with the chat closed, there is almost no difference between fullscreen mode and non fullscreen for player size. I understand that you want the player to be larger, but it is unclear why fullscreen mode doesn't cut it.

**Comment by xRealNeon** [comment]
IDK, I don't like full screen. I know that this is a wired reason, but I really liked the old one, it's like the Netflix one.
Yeah, you can leave the new layout as default, I am asking you if you can add the option for the old one.

**Comment by dyc3** [comment]
Sure, but I can't guarentee that I'll get to it today.

**Comment by dyc3** [comment]
I've changed the player size in #645, should be deployed soonish.
