### ISSUE TITLE
Can't add mp4 video

### ISSUE THREAD

**Issue by Mirimoshka** [dyc3/opentogethertube#736]
### Current Behavior

Previously, mp4 videos ran fine, but now they just don't run and give the error "Failed to get add preview. This is probably a bug, check console for details"

### Expected Behavior

I would like the ability to add mp4 videos to work again

### Steps To Reproduce

1. Create a room
2. Trying to add a new mp4 video from the link 
3. See error "An unknown error occurred when getting add preview. Try again later" and "Failed to get add preview. This is probably a bug, check console for details."

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Can you give me a file to reproduce this with? I'm not getting this error with my existing sample videos.

**Comment by dyc3** [comment]
I think I found the video you were requesting, is it this one? https://samplelib.com/lib/preview/mp4/sample-5s.mp4

**Comment by dyc3** [comment]
I found this great article that explains the format of mp4 videos a little bit: https://sanjeev-pandey.medium.com/understanding-the-mpeg-4-moov-atom-pseudo-streaming-in-mp4-93935e1b9e9a

Long story short, in order to play the video, the server needs the duration. To grab the duration, we grab the first megabyte of the video and scan it for the moov atom. For this particular sample, the moov atom is at the end of the file, so we can't parse the video for metadata.

Looks like I'll have to remove the limit when we grab the video.

**Comment by Mirimoshka** [comment]
Yeah, but no. Then I just checked whether other versions of the videos work. What bothered me more was this format of the link: https://stream.voidboost.cc/40060e90837d14390c0f75b8aa82569e:2022092805:bWQ3bHJ0VGpwYURsMjAybFQ1aHlSdFBsK050TEJFZHVaQVRGNUtYYW9DUWUzL2tlS3dSQWVjSUxxeE5EeFY3ZG92d2ErVVE0bVNDb2ZSNnduNk4ralE9PQ==/4/8/6/7/4/pdbiz.mp4
