### ISSUE TITLE
Full screen not working on ipad

### ISSUE THREAD

**Issue by Scraft02** [dyc3/opentogethertube#839]
### Current Behavior

By pressing the full-screen button the player does not take all of the screen of the ipaad

### Expected Behavior

That the player switches to full-screen mode and takes up the entire screen

### Steps To Reproduce

1) Go to a room on iPad
2) Start a video
3) Put in full screen

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Nothing more, you are on top 👍

**Comment by dyc3** [comment]
I am unable to reproduce this with the iPads I have available to me right now. Could you post a video with the issue you're referring to here?

**Comment by Scraft02** [comment]
https://youtu.be/ejDV_2F-Jl4

I tried on Chrome and OperaGX (on safari the video cannot be preloaded enough to play correctly, I don't know if this is due to my weak tablet or to a compatibility problem (for the moment, no need to open a bug report for that)) So you can see that neither on Chrome nor on OperaGX the player manages to put itself in full screen.

**Comment by dyc3** [comment]
Thank you.

It would appear that the API we use for fullscreen mode just doesn't work in safari. It won't work on any browser on iOS, because all browsers on iOS are required to use safari's WebKit.

I found this forum thread about it: https://developer.apple.com/forums/thread/133248

For now, this seems like it's not fixable.
