### ISSUE TITLE
Password Recovery/Reset feature

### ISSUE THREAD

**Issue by Beethoven-n** [dyc3/opentogethertube#847]
### Is your feature request related to a problem? Please describe.

My partner's currently trying to recover an account, but cannot reset its password.
Turns out, there's not even been an issue raised about the idea!

### Describe the solution you'd like

On login, underneath the password field, there should be a 'Forgot Password?' link. On clicking it, you are prompted for an email to send a password reset link to. On clicking the link, you're prompted for a new password to enter in. The backend then discards your old password, and registers your new one.

### Additional context

It's kinda interesting how this feature isn't implemented yet, considering you are required to log in by email.

**Comment by dyc3** [comment]
The reason this hasn't been implemented yet is because this requires sending email, which is a huge pain in the ass. Also, nobody's had to do a password reset until now. User accounts in general are missing a lot of features that you might consider "standard".

If you email me at `carson.mcmanus1@gmail.com` from the email that the account was made with, I'll see what I can do about recovering that specific account. I don't have a process for this yet.

**Comment by dyc3** [comment]
I added a "Forgot your password?" link to the login form in #1017.
