### ISSUE TITLE
A way to save videos to the playlist where they won't go away if you leave for a while

### ISSUE THREAD

**Issue by Kommynct** [dyc3/opentogethertube#885]
### Is your feature request related to a problem? Please describe.

I hate that when I leave my private room, the videos in the queue all disappear, I understand needing the video not to be running while nobody is in the room, that makes sense, but it shouldn't clear them from the list.

### Describe the solution you'd like

An option to keep them in the list indefinitely

### Additional context

This is the only thing that's worse than cytube haha

**Comment by dyc3** [comment]
I can see how that would be frustrating. I'll see what I can do to make this better. This happens because we intentionally don't persist the full room state when a room is unloaded from the server's memory, just the settings.

In the meantime, there are a few features that exist already that make this slightly less bad:
- Youtube playlists are supported (currently up to 40 videos in a playlist, because I haven't implemented pagination yet, see #172 )
- If you just have a list of URLs, like:
```
http://example.com/foo.mp4
http://youtube.com/watch?v=bar
...etc
```
you can copy and paste that into the add preview box to queue all the videos up at once.

**Comment by Kommynct** [comment]
It seems like this was merged, will this be resolved with the next build?

**Comment by dyc3** [comment]
Queue exporting should already be present in the docker image. If you aren't seeing it, you might need to pull the new image.

**Comment by Kommynct** [comment]
Sick, thanks, donated because of this!!

**Comment by Kommynct** [comment]
Ah, i'd like to re-open this, as this isn't really exactly what I want, yes, I can conveniently save them if I remember to, but sometimes the tab is unloaded, and then all the videos are lost

The text for storing this server-side should be extremely minimal, and it should only apply to permanent rooms, a way to automatically reload the videos once people are back in the room would be wonderful!

**Comment by Kommynct** [comment]
https://github.com/dyc3/opentogethertube/issues/927
